# Generated by Django 3.2 on 2022-09-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220906_0558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
